@echo off
SETLOCAL ENABLEDELAYEDEXPANSION

:: Check if the file already exists
IF EXIST "src/CommitHash.autogenerated" (
    echo The file "src/CommitHash.autogenerated" already exists.
    exit /b 0
)

:: Get the latest commit hash
FOR /F "tokens=*" %%g IN ('git rev-parse HEAD') DO (SET UEVR_COMMIT_HASH=%%g)

:: Get the latest tag
FOR /F "tokens=*" %%t IN ('git describe --tags --always --abbrev^=0') DO (SET UEVR_TAG=%%t)
IF "%UEVR_TAG%"=="" (SET UEVR_TAG=no_tag)

:: Extract tag and commit count since the last tag
SET UEVR_COMMITS_PAST_TAG=0
FOR /F "tokens=*" %%c IN ('git describe --tags --always --long') DO (
    FOR /F "tokens=1,2 delims=-" %%a IN ("%%c") DO (
        SET UEVR_TAG_LONG=%%a
        SET UEVR_TMP_COMMITS_PAST_TAG=%%b
    )
)

:: Ensure the commit count is a valid number
SET /A TEST_NUM=UEVR_TMP_COMMITS_PAST_TAG 2>NUL
IF ERRORLEVEL 1 (
    SET UEVR_COMMITS_PAST_TAG=0
) ELSE (
    SET /A UEVR_COMMITS_PAST_TAG=UEVR_TMP_COMMITS_PAST_TAG
)

:: Get the current branch name
FOR /F "tokens=*" %%b IN ('git rev-parse --abbrev-ref HEAD') DO (SET UEVR_BRANCH=%%b)

:: Get the total number of commits
FOR /F "tokens=*" %%n IN ('git rev-list --count HEAD') DO (SET /A UEVR_TOTAL_COMMITS=%%n)
IF "%UEVR_TOTAL_COMMITS%"=="" (SET UEVR_TOTAL_COMMITS=0)

:: Get the current date and time
FOR /F "tokens=2 delims==" %%a IN ('wmic OS get localdatetime /value') DO (
    SET datetime=%%a
)

SET year=%datetime:~0,4%
SET month=%datetime:~4,2%
SET day=%datetime:~6,2%
SET hour=%datetime:~8,2%
SET minute=%datetime:~10,2%

:: Generate the commit hash header file
(
    echo #pragma once
    echo #define UEVR_COMMIT_HASH "%UEVR_COMMIT_HASH%"
    echo #define UEVR_TAG "%UEVR_TAG%"
    echo #define UEVR_TAG_LONG "%UEVR_TAG_LONG%"
    echo #define UEVR_COMMITS_PAST_TAG %UEVR_COMMITS_PAST_TAG%
    echo #define UEVR_BRANCH "%UEVR_BRANCH%"
    echo #define UEVR_TOTAL_COMMITS %UEVR_TOTAL_COMMITS%
    echo #define UEVR_BUILD_DATE "%day%.%month%.%year%"
    echo #define UEVR_BUILD_TIME "%hour%:%minute%"
) > src/CommitHash.autogenerated

ENDLOCAL
