cmake_minimum_required(VERSION 3.20)
foreach(_required IN ITEMS UEVR_SOURCE_DIR KANANLIB_SOURCE_DIR UEVR_TEST_BINARY_DIR)
    if(NOT DEFINED ${_required})
        message(FATAL_ERROR "Missing ${_required}")
    endif()
endforeach()

set(_fixture "${UEVR_TEST_BINARY_DIR}/source")
set(_build "${UEVR_TEST_BINARY_DIR}/build with spaces")
file(MAKE_DIRECTORY "${_fixture}")
file(WRITE "${_fixture}/dummy.cpp" "void unused_kananlib_fixture() {}\n")
file(WRITE "${_fixture}/CMakeLists.txt" [=[
cmake_minimum_required(VERSION 3.20)
project(KananlibDecodeWindowFixture LANGUAGES CXX)
add_library(kananlib STATIC dummy.cpp)
set(kananlib_SOURCE_DIR "${KANANLIB_SOURCE_DIR}")
include("${UEVR_SOURCE_DIR}/cmake/KananlibDecodeWindow.cmake")
get_target_property(_includes kananlib INTERFACE_INCLUDE_DIRECTORIES)
file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/includes.txt" "${_includes}")
]=])

set(_original "${KANANLIB_SOURCE_DIR}/include/utility/Scan.hpp")
file(SHA256 "${_original}" _original_hash)
foreach(_pass RANGE 1 2)
    execute_process(COMMAND "${CMAKE_COMMAND}" -S "${_fixture}" -B "${_build}"
        "-DUEVR_SOURCE_DIR=${UEVR_SOURCE_DIR}" "-DKANANLIB_SOURCE_DIR=${KANANLIB_SOURCE_DIR}"
        RESULT_VARIABLE _result OUTPUT_VARIABLE _output ERROR_VARIABLE _error)
    if(NOT _result EQUAL 0)
        message(FATAL_ERROR "Backport fixture configuration failed: ${_output}\n${_error}")
    endif()
    file(SHA256 "${_original}" _after_hash)
    if(NOT _original_hash STREQUAL _after_hash)
        message(FATAL_ERROR "The backport modified the shared dependency header")
    endif()
    set(_overlay "${_build}/kananlib-decode-window/include")
    file(SHA256 "${_overlay}/utility/Scan.hpp" _patched_hash)
    if(_pass EQUAL 1)
        set(_first_hash "${_patched_hash}")
    elseif(NOT _first_hash STREQUAL _patched_hash)
        message(FATAL_ERROR "Repeated configuration changed the patched header")
    endif()
    file(READ "${_build}/includes.txt" _includes)
    list(GET _includes 0 _first_include)
    if(NOT _first_include STREQUAL _overlay)
        message(FATAL_ERROR "The backport include path is not published first")
    endif()
    file(SHA256 "${KANANLIB_SOURCE_DIR}/include/utility/Emulation.hpp" _emulation_hash)
    file(SHA256 "${_overlay}/utility/Emulation.hpp" _copied_emulation_hash)
    if(NOT _emulation_hash STREQUAL _copied_emulation_hash)
        message(FATAL_ERROR "Sibling quoted includes do not share the unchanged header overlay")
    endif()
endforeach()

set(_unknown "${UEVR_TEST_BINARY_DIR}/changed dependency")
file(MAKE_DIRECTORY "${_unknown}/include/utility")
file(READ "${_original}" _changed)
file(WRITE "${_unknown}/include/utility/Scan.hpp" "${_changed}\n// unreviewed dependency change\n")
execute_process(COMMAND "${CMAKE_COMMAND}" -S "${_fixture}"
    -B "${UEVR_TEST_BINARY_DIR}/rejected build"
    "-DUEVR_SOURCE_DIR=${UEVR_SOURCE_DIR}" "-DKANANLIB_SOURCE_DIR=${_unknown}"
    RESULT_VARIABLE _result OUTPUT_VARIABLE _output ERROR_VARIABLE _error)
if(_result EQUAL 0 OR NOT _error MATCHES "Kananlib Scan.hpp differs from pinned 49fdf2d")
    message(FATAL_ERROR "An unreviewed dependency change was not rejected: ${_output}\n${_error}")
endif()
message(STATUS "Backport is repeatable, leaves source untouched, and rejects dependency drift")
